on:
  push:
    branches: [ master ]
jobs:
  notif-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.16' # or the specific version required
      - name: push_info_step
        uses: processone/xmpp-notifier@master
        with:
          jid: ${{ secrets.jid }}
          password: ${{ secrets.password }}
          server_host: ${{ secrets.server_host }}
          recipient: ${{ secrets.recipient }}
          message: ${{ github.actor }} pushed to master
          recipient_is_room: true
