name: XMPP Notification
on:
  push:
    branches: [ main ]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send XMPP Notification
        uses: processone/xmpp-notifier@master
        with:
          jid: ${{ secrets.JID }}
          password: ${{ secrets.PASSWORD }}
          server_host: ${{ secrets.SERVER_HOST }}
          recipient: ${{ secrets.RECIPIENT }}
          message: "${{ github.actor }} pushed to ${{ github.repository }}"
          recipient_is_room: true
